boardapp/urls.py
from django.urls import path
from .views import signupfunc ,loginfunc ,listfunc, logoutfunc, detailfunc, goodfunc, readfunc,BoardCreate,get_svg

urlpatterns = [
    path('signup/',signupfunc,name='signup'),
    path('login/',loginfunc,name='login'),
    path('list/',listfunc,name='list'),
    path('logout/',logoutfunc,name='logout'),
    path('detail/<int:pk>',detailfunc,name='detail'),
    path('good/<int:pk>',goodfunc,name='good'),
    path('read/<int:pk>',readfunc,name='read'),
    path('create/',BoardCreate.as_view(),name='create'),
    path('plot/', get_svg, name='plot')

]

boardproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('boardapp.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

boardapp/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone

# Create your models here.
class BoardModel(models.Model):
    title=models.CharField(max_length=100)
    content = models.TextField()
    author = models.CharField(max_length=100)
    images = models.ImageField(upload_to='')
    good = models.IntegerField(null=True,blank=True,default = 0)
    read = models.IntegerField(null=True,blank=True,default = 0)
    readtext = models.CharField(max_length=200,null=True,blank=True,default = '')


class Category(models.Model):
 
    class Meta:
        #カテゴリ
        verbose_name ="カテゴリ"
        verbose_name_plural ="カテゴリ"
      
#カラム名の定義
    category_name = models.CharField(max_length=255,unique=True)
 
    def __str__(self):
        return self.category_name
 
 
class Kakeibo(models.Model):
 
    class Meta:
      
        verbose_name ="家計簿"
        verbose_name_plural ="家計簿"
 
    #カラムの定義
    date = models.DateField("日付",default=datetime.now)
    category = models.ForeignKey(Category, on_delete = models.PROTECT, verbose_name="カテゴリ")
    money = models.IntegerField("金額", help_text="単位は日本円")
    quantity = models.IntegerField(verbose_name="数量",default=0)
    memo = models.CharField(verbose_name="メモ", max_length=500)
    regist_date = models.DateTimeField(default=timezone.now)
 
    def __str__(self):
        return self.memo

boardapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import BoardModel
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.urls import reverse_lazy

import matplotlib
#バックエンドを指定
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import io
from django.http import HttpResponse


# Create your views here.

def signupfunc(request):
    if request.method == 'POST':
        username_request=request.POST['username']
        password_request=request.POST['password']
        try:
            User.objects.get(username=username_request)
            return render(request,'signup.html',{'error':'このユーザーはすでに登録されています'})

        except:
            user = User.objects.create_user(username_request, '', password_request)
            return render(request,'signup.html',{'some':100})
    return render(request,'signup.html',{'some':100})

def loginfunc(request):
    if request.method == 'POST':
        username_request=request.POST['username']
        password_request=request.POST['password']    
        user = authenticate(username=username_request, password=password_request)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('list')
        else:
            return redirect('login')
    return render(request,'login.html')
        # Return an 'invalid login' error message.

@login_required
def listfunc(request):
    object_list = BoardModel.objects.all()
    return render(request , 'list.html', {'object_list':object_list})

def logoutfunc(request):
    logout(request)
    return redirect('login')

def detailfunc(request,pk):
    object = BoardModel.objects.get(pk=pk)
    return render(request,'detail.html',{'object':object})
    
def goodfunc(request,pk):
    post = BoardModel.objects.get(pk=pk)
    post.good = post.good + 1
    post.save()
    return redirect('list')

def readfunc(request,pk):
    post = BoardModel.objects.get(pk=pk)
    post2 = request.user.get_username()
    if post2 in post.readtext:
        return redirect('list')
    else:
        post.read += 1
        post.readtext = post.readtext + ' ' + post2
        post.save()
        return redirect('list')

class BoardCreate(CreateView):
    template_name = 'create.html'
    model = BoardModel
    fields = ('title','content','author','images')
    success_url = reverse_lazy('list')


#グラフ作成
def setPlt():
    x = ["07/01", "07/02", "07/03", "07/04", "07/05", "07/06", "07/07"]
    y = [9000000, 5, 0, 5, 6, 10, 2]
    plt.bar(x, y, color='#00d5ff')
    plt.title(r"$\bf{Running Trend  -2020/07/07}$", color='#3407ba')
    plt.xlabel("Date")
    plt.ylabel("km")

# SVG化
def plt2svg():
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight')
    s = buf.getvalue()
    buf.close()
    return s

# 実行するビュー関数
def get_svg(request):
    setPlt()  
    svg = plt2svg()  #SVG化
    plt.cla()  # グラフをリセット
    response = HttpResponse(svg, content_type='image/svg+xml')
    return response

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    {% block customcss %}
    {% endblock customcss %}

    <title>Hello, world!</title>
  </head>
  <body>
    {% block header %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<form action='' method='POST' enctype="multipart/form-data">{% csrf_token %}
        <p>タイトル：<input type='text' name='title'></p>
        <p>内容：<input type='text' name='content'></p>
        <p>画像：<input type='file' name='images'></p>
        <input type="hidden" name='author' value='{{ user.username }}'>



<input type='submit' value='作成する'>
</form>
{% else %}
ログインしてください。
{% endif%}
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}


{% block header %}
<div class="alert alert-primary" role="alert">
    個別投稿
</div>
{% endblock header %}

{% block content %}
<div class='container'>
    <div class="alert alert-success" role="alert">
        <p> タイトル：{{object.title}}</p>
        <p>投稿者：{{object.author}}</p>
        <p>内容：{{object.content}}</p>
        <p><img src="{{object.images.url}}" width=100></p>
        <a href="{% url 'good' object.pk %}" class="btn btn-primary " role="button" aria-pressed="true">いいね</a>
        <a href="{% url 'read' object.pk %}" class="btn btn-secondary " role="button" aria-pressed="true">既読</a>
    </div>
</div>

{% endblock content %}

templates/diary_list.html
#テンプレート追記例
#diary_list.html

app_name = 'diary'
<img src="{% url 'diary:plot' %}" width=600 height=600>

templates/list.html
{% extends 'base.html' %}

{% block customcss %}
{% endblock customcss %}


{% block header %}
<div class="alert alert-primary" role="alert">
    SNS
</div>
{% endblock header %}

{% block content %}
<div class='container'>
    {% for item in object_list %}
    <div class="alert alert-success" role="alert">
        <p> タイトル：<a href = "{% url 'detail' item.pk %}">{{item.title}}</a></p>
        <p>投稿者：{{item.author}}</p>
        <a href="#" class="btn btn-primary " role="button" aria-pressed="true">いいね：{{item.good}}</a>
        <a href="#" class="btn btn-secondary " role="button" aria-pressed="true">既読：{{item.read}}人</a>
    </div>
    {% endfor  %}
    <a href="{% url 'logout'%}">ログアウト</a>
</div>

{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<form class="form-signin" method='POST' action='' >{% csrf_token %}
    <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please login</h1>
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" name= 'username' placeholder="username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control"  name='password' placeholder="Password" required>
    <div class="checkbox mb-3">

    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">log in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
  </form>

{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel='stylesheet' type='text/css' href="{% static 'style.css' %}">
{% endblock customcss %}


{% block content %}
<form class="form-signin" method='POST' action='' >{% csrf_token %}
    <img class="mb-4" src="/docs/4.4/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
    {% if error %}
    {{ error }}
    {% endif %}
    <label for="inputEmail" class="sr-only">Email address</label>
    <input type="email" id="inputEmail" class="form-control" name= 'username' placeholder="username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control"  name='password' placeholder="Password" required>
    <div class="checkbox mb-3">

    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2020</p>
  </form>

{% endblock content %}